### ISSUE TITLE
GIMME DAT SWEET SCRAPER

### ISSUE THREAD

**Issue by Nehhaket** [elochim-siemasz/FakeU#1]

**Comment by elo-siema** [comment]
https://gist.github.com/kadnan/07fa4c3fd2f46f8a079ace39be90e211

**Comment by elo-siema** [comment]
chuj mi w dupe i na imie

**Comment by Nehhaket** [comment]
title <string>:
    #offerdescription > .offer-titlebox > h1

id <string>: //like 'ID ogłoszenia: %Listing.id%'
    #offerdescription > .offer-titlebox > .offer-titlebox__details > em > small

price <string>: //like '%price(with spaces)% zł'
    #offeractions > .price-label > strong

description <string>:
    #offerdescription > #textContent

**Comment by elo-siema** [comment]
Thank you Marcin very cool

**Comment by Nehhaket** [comment]
Uri building:
    "https://www.olx.pl/oferty/q-" + słowo + "-" + klucz + ... + "/"
    + ?page=" + numerStrony

Listings list:
    #offers_table > tbody > tr.wrap > td > div > table > tbody > tr > td > div > h3 > a

**Comment by Nehhaket** [comment]
Uri building:
    += "?spellchecker=off"

**Comment by Nehhaket** [comment]
If Listings list is empty:
    .emptynew

**Comment by Nehhaket** [comment]
Listings list:
    //*[@id='offers_table']/tbody/tr[contains(@class, 'wrap')]/td/div/table/tbody/tr/td/div/h3/a/@href

**Comment by Nehhaket** [comment]
Zabij mnie, github podlinkowuje ludzi przy @

**Comment by Nehhaket** [comment]
class z małej
